name: gxp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  http: ^0.13.3
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_native_splash: ^1.2.1
  shared_preferences: ^2.0.6
  flutter_webview_plugin: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  page_transition: ^2.0.2
  flutter_launcher_icons:
  webview_flutter: ^2.0.12
  dartz:
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.9
  transparent_image: ^2.0.0
  cached_network_image: ^3.1.0
  

dev_dependencies:
  build_runner: ^2.1.1 
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/icons/
    - lib/assets/icons/svg/
    - lib/assets/images/
    - lib/assets/images/flags/
    - lib/assets/images/profile/
    - lib/assets/logo/
    - lib/assets/logo/svg/
    - .env 
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true
