import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
//import 'package:flutter_svg_provider/flutter_svg_provider.dart';

class NatDSIcons {
  static Widget loadLogo(String name, [Color? color, double? width, double? heigth]) {
    final String assetName = './lib/assets/logo/svg/$name.svg';
    final Widget image = SvgPicture.asset(
      assetName,
      width: width,
      height: heigth,
      color: color,
      semanticsLabel: "Logo tipo",
    );
    return image;
  }

  static Widget load(String name, Color? color, [double? width, double? height]) {
    final String assetName = './lib/assets/icons/svg/$name.svg';

    if (width != null && height != null) {
      return SvgPicture.asset(
        assetName,
        width: width,
        height: height,
        color: color == null ? Colors.orange.shade400 : color,
      );
    } else {
      return SvgPicture.asset(
        assetName,
        color: color == null ? Colors.orange.shade400 : color,
      );
    }
  }

  static Widget filledActionAdd({Color? color, double? width, double? height}) => load('filled-action-add', color, width, height);
  static Widget filledActionCancel({Color? color, double? width, double? height}) => load('filled-action-cancel', color, width, height);
  static Widget filledActionCheck({Color? color, double? width, double? height}) => load('filled-action-check', color, width, height);
  static Widget filledActionClock({Color? color, double? width, double? height}) => load('filled-action-clock', color, width, height);
  static Widget filledActionDelete({Color? color, double? width, double? height}) => load('filled-action-delete', color, width, height);
  static Widget filledActionLove({Color? color, double? width, double? height}) => load('filled-action-love', color, width, height);
  static Widget filledActionNewrequest({Color? color, double? width, double? height}) => load('filled-action-newrequest', color, width, height);
  static Widget filledActionRating({Color? color, double? width, double? height}) => load('filled-action-rating', color, width, height);
  static Widget filledActionRequest({Color? color, double? width, double? height}) => load('filled-action-request', color, width, height);
  static Widget filledActionSubtract({Color? color, double? width, double? height}) => load('filled-action-subtract', color, width, height);
  static Widget filledBrandAvonshorthand({Color? color, double? width, double? height}) => load('filled-brand-avonshorthand', color, width, height);
  static Widget filledBrandFacebook({Color? color, double? width, double? height}) => load('filled-brand-facebook', color, width, height);
  static Widget filledBrandGoogle({Color? color, double? width, double? height}) => load('filled-brand-google', color, width, height);
  static Widget filledBrandInstagram({Color? color, double? width, double? height}) => load('filled-brand-instagram', color, width, height);
  static Widget filledBrandLinkedin({Color? color, double? width, double? height}) => load('filled-brand-linkedin', color, width, height);
  static Widget filledBrandNaturarosacea({Color? color, double? width, double? height}) => load('filled-brand-naturarosacea', color, width, height);
  static Widget filledBrandPinterest({Color? color, double? width, double? height}) => load('filled-brand-pinterest', color, width, height);
  static Widget filledBrandSpotify({Color? color, double? width, double? height}) => load('filled-brand-spotify', color, width, height);
  static Widget filledBrandTwitter({Color? color, double? width, double? height}) => load('filled-brand-twitter', color, width, height);
  static Widget filledBrandWhatsapp({Color? color, double? width, double? height}) => load('filled-brand-whatsapp', color, width, height);
  static Widget filledBrandYoutube({Color? color, double? width, double? height}) => load('filled-brand-youtube', color, width, height);
  static Widget filledContentChannel({Color? color, double? width, double? height}) => load('filled-content-channel', color, width, height);
  static Widget filledContentDivulgation({Color? color, double? width, double? height}) => load('filled-content-divulgation', color, width, height);
  static Widget filledContentQuote({Color? color, double? width, double? height}) => load('filled-content-quote', color, width, height);
  static Widget filledDefaultMockup({Color? color, double? width, double? height}) => load('filled-default-mockup', color, width, height);
  static Widget filledFinanceCharging({Color? color, double? width, double? height}) => load('filled-finance-charging', color, width, height);
  static Widget filledFinanceInvoice({Color? color, double? width, double? height}) => load('filled-finance-invoice', color, width, height);
  static Widget filledFinanceMoney({Color? color, double? width, double? height}) => load('filled-finance-money', color, width, height);
  static Widget filledFinancePaymentlink({Color? color, double? width, double? height}) => load('filled-finance-paymentlink', color, width, height);
  static Widget filledFinancePaymentnotapproved({Color? color, double? width, double? height}) => load('filled-finance-paymentnotapproved', color, width, height);
  static Widget filledMediaPause({Color? color, double? width, double? height}) => load('filled-media-pause', color, width, height);
  static Widget filledMediaPlay({Color? color, double? width, double? height}) => load('filled-media-play', color, width, height);
  static Widget filledMediaStop({Color? color, double? width, double? height}) => load('filled-media-stop', color, width, height);
  static Widget filledNavigationArrowbottom({Color? color, double? width, double? height}) => load('filled-navigation-arrowbottom', color, width, height);
  static Widget filledNavigationArrowleft({Color? color, double? width, double? height}) => load('filled-navigation-arrowleft', color, width, height);
  static Widget filledNavigationArrowright({Color? color, double? width, double? height}) => load('filled-navigation-arrowright', color, width, height);
  static Widget filledNavigationArrowtop({Color? color, double? width, double? height}) => load('filled-navigation-arrowtop', color, width, height);
  static Widget filledNavigationDirectionleft({Color? color, double? width, double? height}) => load('filled-navigation-directionleft', color, width, height);
  static Widget filledNavigationDirectionright({Color? color, double? width, double? height}) => load('filled-navigation-directionright', color, width, height);
  static Widget filledNavigationDirectiontbottom({Color? color, double? width, double? height}) => load('filled-navigation-directiontbottom', color, width, height);
  static Widget filledNavigationDirectiontop({Color? color, double? width, double? height}) => load('filled-navigation-directiontop', color, width, height);
  static Widget filledNavigationHome({Color? color, double? width, double? height}) => load('filled-navigation-home', color, width, height);
  static Widget filledNavigationMenu({Color? color, double? width, double? height}) => load('filled-navigation-menu', color, width, height);
  static Widget filledNavigationMore({Color? color, double? width, double? height}) => load('filled-navigation-more', color, width, height);
  static Widget filledNavigationSetbottom({Color? color, double? width, double? height}) => load('filled-navigation-setbottom', color, width, height);
  static Widget filledNavigationSetleft({Color? color, double? width, double? height}) => load('filled-navigation-setleft', color, width, height);
  static Widget filledNavigationSetright({Color? color, double? width, double? height}) => load('filled-navigation-setright', color, width, height);
  static Widget filledNavigationSettop({Color? color, double? width, double? height}) => load('filled-navigation-settop', color, width, height);
  static Widget filledPlaceTruck({Color? color, double? width, double? height}) => load('filled-place-truck', color, width, height);
  static Widget filledProductBrandsproduct({Color? color, double? width, double? height}) => load('filled-product-brandsproduct', color, width, height);
  static Widget filledSocialMyprofile({Color? color, double? width, double? height}) => load('filled-social-myprofile', color, width, height);
  static Widget filledToggleIndeterminatecheckbox({Color? color, double? width, double? height}) => load('filled-toggle-indeterminatecheckbox', color, width, height);
  static Widget outlinedActionAdd({Color? color, double? width, double? height}) => load('outlined-action-add', color, width, height);
  static Widget outlinedActionAddproduct({Color? color, double? width, double? height}) => load('outlined-action-addproduct', color, width, height);
  static Widget outlinedActionAttachment({Color? color, double? width, double? height}) => load('outlined-action-attachment', color, width, height);
  static Widget outlinedActionAutofilter({Color? color, double? width, double? height}) => load('outlined-action-autofilter', color, width, height);
  static Widget outlinedActionCalendar({Color? color, double? width, double? height}) => load('outlined-action-calendar', color, width, height);
  static Widget outlinedActionCamerachange({Color? color, double? width, double? height}) => load('outlined-action-camerachange', color, width, height);
  static Widget outlinedActionCancel({Color? color, double? width, double? height}) => load('outlined-action-cancel', color, width, height);
  static Widget outlinedActionChange({Color? color, double? width, double? height}) => load('outlined-action-change', color, width, height);
  static Widget outlinedActionCheck({Color? color, double? width, double? height}) => load('outlined-action-check', color, width, height);
  static Widget outlinedActionClock({Color? color, double? width, double? height}) => load('outlined-action-clock', color, width, height);
  static Widget outlinedActionClosedbox({Color? color, double? width, double? height}) => load('outlined-action-closedbox', color, width, height);
  static Widget outlinedActionCopy({Color? color, double? width, double? height}) => load('outlined-action-copy', color, width, height);
  static Widget outlinedActionCopylink({Color? color, double? width, double? height}) => load('outlined-action-copylink', color, width, height);
  static Widget outlinedActionCycle({Color? color, double? width, double? height}) => load('outlined-action-cycle', color, width, height);
  static Widget outlinedActionDelete({Color? color, double? width, double? height}) => load('outlined-action-delete', color, width, height);
  static Widget outlinedActionDone({Color? color, double? width, double? height}) => load('outlined-action-done', color, width, height);
  static Widget outlinedActionDownload({Color? color, double? width, double? height}) => load('outlined-action-download', color, width, height);
  static Widget outlinedActionEdit({Color? color, double? width, double? height}) => load('outlined-action-edit', color, width, height);
  static Widget outlinedActionFavorite({Color? color, double? width, double? height}) => load('outlined-action-favorite', color, width, height);
  static Widget outlinedActionFilter({Color? color, double? width, double? height}) => load('outlined-action-filter', color, width, height);
  static Widget outlinedActionFrame({Color? color, double? width, double? height}) => load('outlined-action-frame', color, width, height);
  static Widget outlinedActionGridsquare({Color? color, double? width, double? height}) => load('outlined-action-gridsquare', color, width, height);
  static Widget outlinedActionHelp({Color? color, double? width, double? height}) => load('outlined-action-help', color, width, height);
  static Widget outlinedActionHistory({Color? color, double? width, double? height}) => load('outlined-action-history', color, width, height);
  static Widget outlinedActionLightoff({Color? color, double? width, double? height}) => load('outlined-action-lightoff', color, width, height);
  static Widget outlinedActionLighton({Color? color, double? width, double? height}) => load('outlined-action-lighton', color, width, height);
  static Widget outlinedActionLike({Color? color, double? width, double? height}) => load('outlined-action-like', color, width, height);
  static Widget outlinedActionList({Color? color, double? width, double? height}) => load('outlined-action-list', color, width, height);
  static Widget outlinedActionLove({Color? color, double? width, double? height}) => load('outlined-action-love', color, width, height);
  static Widget outlinedActionMic({Color? color, double? width, double? height}) => load('outlined-action-mic', color, width, height);
  static Widget outlinedActionMicrec({Color? color, double? width, double? height}) => load('outlined-action-micrec', color, width, height);
  static Widget outlinedActionNewregister({Color? color, double? width, double? height}) => load('outlined-action-newregister', color, width, height);
  static Widget outlinedActionNewrequest({Color? color, double? width, double? height}) => load('outlined-action-newrequest', color, width, height);
  static Widget outlinedActionOrder({Color? color, double? width, double? height}) => load('outlined-action-order', color, width, height);
  static Widget outlinedActionPhone({Color? color, double? width, double? height}) => load('outlined-action-phone', color, width, height);
  static Widget outlinedActionPrint({Color? color, double? width, double? height}) => load('outlined-action-print', color, width, height);
  static Widget outlinedActionQr({Color? color, double? width, double? height}) => load('outlined-action-qr', color, width, height);
  static Widget outlinedActionRating({Color? color, double? width, double? height}) => load('outlined-action-rating', color, width, height);
  static Widget outlinedActionRecycle({Color? color, double? width, double? height}) => load('outlined-action-recycle', color, width, height);
  static Widget outlinedActionRequest({Color? color, double? width, double? height}) => load('outlined-action-request', color, width, height);
  static Widget outlinedActionRequestspecial({Color? color, double? width, double? height}) => load('outlined-action-requestspecial', color, width, height);
  static Widget outlinedActionRunningclock({Color? color, double? width, double? height}) => load('outlined-action-runningclock', color, width, height);
  static Widget outlinedActionSave({Color? color, double? width, double? height}) => load('outlined-action-save', color, width, height);
  static Widget outlinedActionSchedule({Color? color, double? width, double? height}) => load('outlined-action-schedule', color, width, height);
  static Widget outlinedActionSearch({Color? color, double? width, double? height}) => load('outlined-action-search', color, width, height);
  static Widget outlinedActionSelectedalllines({Color? color, double? width, double? height}) => load('outlined-action-selectedalllines', color, width, height);
  static Widget outlinedActionSend({Color? color, double? width, double? height}) => load('outlined-action-send', color, width, height);
  static Widget outlinedActionSettings({Color? color, double? width, double? height}) => load('outlined-action-settings', color, width, height);
  static Widget outlinedActionShare({Color? color, double? width, double? height}) => load('outlined-action-share', color, width, height);
  static Widget outlinedActionShareios({Color? color, double? width, double? height}) => load('outlined-action-shareios', color, width, height);
  static Widget outlinedActionSubtract({Color? color, double? width, double? height}) => load('outlined-action-subtract', color, width, height);
  static Widget outlinedActionText({Color? color, double? width, double? height}) => load('outlined-action-text', color, width, height);
  static Widget outlinedActionUpdate({Color? color, double? width, double? height}) => load('outlined-action-update', color, width, height);
  static Widget outlinedActionUpload({Color? color, double? width, double? height}) => load('outlined-action-upload', color, width, height);
  static Widget outlinedActionVisibility({Color? color, double? width, double? height}) => load('outlined-action-visibility', color, width, height);
  static Widget outlinedActionVisibilityoff({Color? color, double? width, double? height}) => load('outlined-action-visibilityoff', color, width, height);
  static Widget outlinedAlertCancel({Color? color, double? width, double? height}) => load('outlined-alert-cancel', color, width, height);
  static Widget outlinedAlertCheck({Color? color, double? width, double? height}) => load('outlined-alert-check', color, width, height);
  static Widget outlinedAlertEmpty({Color? color, double? width, double? height}) => load('outlined-alert-empty', color, width, height);
  static Widget outlinedAlertIndeterminate({Color? color, double? width, double? height}) => load('outlined-alert-indeterminate', color, width, height);
  static Widget outlinedAlertInfo({Color? color, double? width, double? height}) => load('outlined-alert-info', color, width, height);
  static Widget outlinedAlertNotification({Color? color, double? width, double? height}) => load('outlined-alert-notification', color, width, height);
  static Widget outlinedAlertNotificationsbadge({Color? color, double? width, double? height}) => load('outlined-alert-notificationsbadge', color, width, height);
  static Widget outlinedAlertWarning({Color? color, double? width, double? height}) => load('outlined-alert-warning', color, width, height);
  static Widget outlinedCommunicationChat({Color? color, double? width, double? height}) => load('outlined-communication-chat', color, width, height);
  static Widget outlinedCommunicationEmail({Color? color, double? width, double? height}) => load('outlined-communication-email', color, width, height);
  static Widget outlinedCommunicationHelp({Color? color, double? width, double? height}) => load('outlined-communication-help', color, width, height);
  static Widget outlinedCommunicationMessage({Color? color, double? width, double? height}) => load('outlined-communication-message', color, width, height);
  static Widget outlinedCommunicationOccurrence({Color? color, double? width, double? height}) => load('outlined-communication-occurrence', color, width, height);
  static Widget outlinedCommunicationPhoneringing({Color? color, double? width, double? height}) => load('outlined-communication-phoneringing', color, width, height);
  static Widget outlinedCommunicationReademail({Color? color, double? width, double? height}) => load('outlined-communication-reademail', color, width, height);
  static Widget outlinedCommunicationSignal({Color? color, double? width, double? height}) => load('outlined-communication-signal', color, width, height);
  static Widget outlinedCommunicationSpeaker({Color? color, double? width, double? height}) => load('outlined-communication-speaker', color, width, height);
  static Widget outlinedCommunicationTreatment({Color? color, double? width, double? height}) => load('outlined-communication-treatment', color, width, height);
  static Widget outlinedContentAdddocument({Color? color, double? width, double? height}) => load('outlined-content-adddocument', color, width, height);
  static Widget outlinedContentAgility({Color? color, double? width, double? height}) => load('outlined-content-agility', color, width, height);
  static Widget outlinedContentAsleep({Color? color, double? width, double? height}) => load('outlined-content-asleep', color, width, height);
  static Widget outlinedContentBellringing({Color? color, double? width, double? height}) => load('outlined-content-bellringing', color, width, height);
  static Widget outlinedContentBook({Color? color, double? width, double? height}) => load('outlined-content-book', color, width, height);
  static Widget outlinedContentBrightness({Color? color, double? width, double? height}) => load('outlined-content-brightness', color, width, height);
  static Widget outlinedContentChangeview({Color? color, double? width, double? height}) => load('outlined-content-changeview', color, width, height);
  static Widget outlinedContentChannel({Color? color, double? width, double? height}) => load('outlined-content-channel', color, width, height);
  static Widget outlinedContentChristmascard({Color? color, double? width, double? height}) => load('outlined-content-christmascard', color, width, height);
  static Widget outlinedContentCloud({Color? color, double? width, double? height}) => load('outlined-content-cloud', color, width, height);
  static Widget outlinedContentConsistency({Color? color, double? width, double? height}) => load('outlined-content-consistency', color, width, height);
  static Widget outlinedContentDivulgation({Color? color, double? width, double? height}) => load('outlined-content-divulgation', color, width, height);
  static Widget outlinedContentEducation({Color? color, double? width, double? height}) => load('outlined-content-education', color, width, height);
  static Widget outlinedContentExchangereports({Color? color, double? width, double? height}) => load('outlined-content-exchangereports', color, width, height);
  static Widget outlinedContentFlower({Color? color, double? width, double? height}) => load('outlined-content-flower', color, width, height);
  static Widget outlinedContentFragrance({Color? color, double? width, double? height}) => load('outlined-content-fragrance', color, width, height);
  static Widget outlinedContentGallery({Color? color, double? width, double? height}) => load('outlined-content-gallery', color, width, height);
  static Widget outlinedContentGift({Color? color, double? width, double? height}) => load('outlined-content-gift', color, width, height);
  static Widget outlinedContentGlobal({Color? color, double? width, double? height}) => load('outlined-content-global', color, width, height);
  static Widget outlinedContentHandbag({Color? color, double? width, double? height}) => load('outlined-content-handbag', color, width, height);
  static Widget outlinedContentHandcare({Color? color, double? width, double? height}) => load('outlined-content-handcare', color, width, height);
  static Widget outlinedContentHandglobal({Color? color, double? width, double? height}) => load('outlined-content-handglobal', color, width, height);
  static Widget outlinedContentHands({Color? color, double? width, double? height}) => load('outlined-content-hands', color, width, height);
  static Widget outlinedContentHealth({Color? color, double? width, double? height}) => load('outlined-content-health', color, width, height);
  static Widget outlinedContentHealthy({Color? color, double? width, double? height}) => load('outlined-content-healthy', color, width, height);
  static Widget outlinedContentIndicator({Color? color, double? width, double? height}) => load('outlined-content-indicator', color, width, height);
  static Widget outlinedContentItemlist({Color? color, double? width, double? height}) => load('outlined-content-itemlist', color, width, height);
  static Widget outlinedContentLeafs({Color? color, double? width, double? height}) => load('outlined-content-leafs', color, width, height);
  static Widget outlinedContentLifebuoy({Color? color, double? width, double? height}) => load('outlined-content-lifebuoy', color, width, height);
  static Widget outlinedContentLock({Color? color, double? width, double? height}) => load('outlined-content-lock', color, width, height);
  static Widget outlinedContentMagic({Color? color, double? width, double? height}) => load('outlined-content-magic', color, width, height);
  static Widget outlinedContentMaintenance({Color? color, double? width, double? height}) => load('outlined-content-maintenance', color, width, height);
  static Widget outlinedContentMedal({Color? color, double? width, double? height}) => load('outlined-content-medal', color, width, height);
  static Widget outlinedContentMenu({Color? color, double? width, double? height}) => load('outlined-content-menu', color, width, height);
  static Widget outlinedContentMirror({Color? color, double? width, double? height}) => load('outlined-content-mirror', color, width, height);
  static Widget outlinedContentPassword({Color? color, double? width, double? height}) => load('outlined-content-password', color, width, height);
  static Widget outlinedContentPlanb({Color? color, double? width, double? height}) => load('outlined-content-planb', color, width, height);
  static Widget outlinedContentProductshowcase({Color? color, double? width, double? height}) => load('outlined-content-productshowcase', color, width, height);
  static Widget outlinedContentProdutivity({Color? color, double? width, double? height}) => load('outlined-content-produtivity', color, width, height);
  static Widget outlinedContentRainycloud({Color? color, double? width, double? height}) => load('outlined-content-rainycloud', color, width, height);
  static Widget outlinedContentReport({Color? color, double? width, double? height}) => load('outlined-content-report', color, width, height);
  static Widget outlinedContentSaleinsight({Color? color, double? width, double? height}) => load('outlined-content-saleinsight', color, width, height);
  static Widget outlinedContentSnow({Color? color, double? width, double? height}) => load('outlined-content-snow', color, width, height);
  static Widget outlinedContentStore({Color? color, double? width, double? height}) => load('outlined-content-store', color, width, height);
  static Widget outlinedContentSun({Color? color, double? width, double? height}) => load('outlined-content-sun', color, width, height);
  static Widget outlinedContentSunandcloud({Color? color, double? width, double? height}) => load('outlined-content-sunandcloud', color, width, height);
  static Widget outlinedContentUnavailable({Color? color, double? width, double? height}) => load('outlined-content-unavailable', color, width, height);
  static Widget outlinedContentVirtualmirror({Color? color, double? width, double? height}) => load('outlined-content-virtualmirror', color, width, height);
  static Widget outlinedContentWellness({Color? color, double? width, double? height}) => load('outlined-content-wellness', color, width, height);
  static Widget outlinedContentWifi({Color? color, double? width, double? height}) => load('outlined-content-wifi', color, width, height);
  static Widget outlinedDefaultMockup({Color? color, double? width, double? height}) => load('outlined-default-mockup', color, width, height);
  static Widget outlinedFinanceBag({Color? color, double? width, double? height}) => load('outlined-finance-bag', color, width, height);
  static Widget outlinedFinanceBank({Color? color, double? width, double? height}) => load('outlined-finance-bank', color, width, height);
  static Widget outlinedFinanceCards({Color? color, double? width, double? height}) => load('outlined-finance-cards', color, width, height);
  static Widget outlinedFinanceCharging({Color? color, double? width, double? height}) => load('outlined-finance-charging', color, width, height);
  static Widget outlinedFinanceCreditcard({Color? color, double? width, double? height}) => load('outlined-finance-creditcard', color, width, height);
  static Widget outlinedFinanceDebit({Color? color, double? width, double? height}) => load('outlined-finance-debit', color, width, height);
  static Widget outlinedFinanceDiscount({Color? color, double? width, double? height}) => load('outlined-finance-discount', color, width, height);
  static Widget outlinedFinanceIdcard({Color? color, double? width, double? height}) => load('outlined-finance-idcard', color, width, height);
  static Widget outlinedFinanceInvoice({Color? color, double? width, double? height}) => load('outlined-finance-invoice', color, width, height);
  static Widget outlinedFinanceLittlemachine({Color? color, double? width, double? height}) => load('outlined-finance-littlemachine', color, width, height);
  static Widget outlinedFinanceMoney({Color? color, double? width, double? height}) => load('outlined-finance-money', color, width, height);
  static Widget outlinedFinanceMoneypaper({Color? color, double? width, double? height}) => load('outlined-finance-moneypaper', color, width, height);
  static Widget outlinedFinancePaid({Color? color, double? width, double? height}) => load('outlined-finance-paid', color, width, height);
  static Widget outlinedFinancePaymentlink({Color? color, double? width, double? height}) => load('outlined-finance-paymentlink', color, width, height);
  static Widget outlinedFinancePaymentnotapproved({Color? color, double? width, double? height}) => load('outlined-finance-paymentnotapproved', color, width, height);
  static Widget outlinedFinancePayreference({Color? color, double? width, double? height}) => load('outlined-finance-payreference', color, width, height);
  static Widget outlinedFinancePromotion({Color? color, double? width, double? height}) => load('outlined-finance-promotion', color, width, height);
  static Widget outlinedFinanceScancard({Color? color, double? width, double? height}) => load('outlined-finance-scancard', color, width, height);
  static Widget outlinedFinanceShoppingcart({Color? color, double? width, double? height}) => load('outlined-finance-shoppingcart', color, width, height);
  static Widget outlinedFinanceShoppingcartproduct({Color? color, double? width, double? height}) => load('outlined-finance-shoppingcartproduct', color, width, height);
  static Widget outlinedFinanceSuitcase({Color? color, double? width, double? height}) => load('outlined-finance-suitcase', color, width, height);
  static Widget outlinedFinanceTagdiscount({Color? color, double? width, double? height}) => load('outlined-finance-tagdiscount', color, width, height);
  static Widget outlinedFinanceTransfermoney({Color? color, double? width, double? height}) => load('outlined-finance-transfermoney', color, width, height);
  static Widget outlinedMakeupEyebrow({Color? color, double? width, double? height}) => load('outlined-makeup-eyebrow', color, width, height);
  static Widget outlinedMakeupEyelashes({Color? color, double? width, double? height}) => load('outlined-makeup-eyelashes', color, width, height);
  static Widget outlinedMakeupEyeliner({Color? color, double? width, double? height}) => load('outlined-makeup-eyeliner', color, width, height);
  static Widget outlinedMakeupFace({Color? color, double? width, double? height}) => load('outlined-makeup-face', color, width, height);
  static Widget outlinedMakeupMouth({Color? color, double? width, double? height}) => load('outlined-makeup-mouth', color, width, height);
  static Widget outlinedMediaApp({Color? color, double? width, double? height}) => load('outlined-media-app', color, width, height);
  static Widget outlinedMediaCamera({Color? color, double? width, double? height}) => load('outlined-media-camera', color, width, height);
  static Widget outlinedMediaCameraunavailable({Color? color, double? width, double? height}) => load('outlined-media-cameraunavailable', color, width, height);
  static Widget outlinedMediaMonitor({Color? color, double? width, double? height}) => load('outlined-media-monitor', color, width, height);
  static Widget outlinedMediaPlay({Color? color, double? width, double? height}) => load('outlined-media-play', color, width, height);
  static Widget outlinedNavigationArrowbottom({Color? color, double? width, double? height}) => load('outlined-navigation-arrowbottom', color, width, height);
  static Widget outlinedNavigationArrowleft({Color? color, double? width, double? height}) => load('outlined-navigation-arrowleft', color, width, height);
  static Widget outlinedNavigationArrowright({Color? color, double? width, double? height}) => load('outlined-navigation-arrowright', color, width, height);
  static Widget outlinedNavigationArrowtop({Color? color, double? width, double? height}) => load('outlined-navigation-arrowtop', color, width, height);
  static Widget outlinedNavigationClose({Color? color, double? width, double? height}) => load('outlined-navigation-close', color, width, height);
  static Widget outlinedNavigationDirectionbottom({Color? color, double? width, double? height}) => load('outlined-navigation-directionbottom', color, width, height);
  static Widget outlinedNavigationDirectionleft({Color? color, double? width, double? height}) => load('outlined-navigation-directionleft', color, width, height);
  static Widget outlinedNavigationDirectionright({Color? color, double? width, double? height}) => load('outlined-navigation-directionright', color, width, height);
  static Widget outlinedNavigationDirectiontop({Color? color, double? width, double? height}) => load('outlined-navigation-directiontop', color, width, height);
  static Widget outlinedNavigationExit({Color? color, double? width, double? height}) => load('outlined-navigation-exit', color, width, height);
  static Widget outlinedNavigationGoback({Color? color, double? width, double? height}) => load('outlined-navigation-goback', color, width, height);
  static Widget outlinedNavigationGofront({Color? color, double? width, double? height}) => load('outlined-navigation-gofront', color, width, height);
  static Widget outlinedNavigationHome({Color? color, double? width, double? height}) => load('outlined-navigation-home', color, width, height);
  static Widget outlinedNavigationMenu({Color? color, double? width, double? height}) => load('outlined-navigation-menu', color, width, height);
  static Widget outlinedPlaceBus({Color? color, double? width, double? height}) => load('outlined-place-bus', color, width, height);
  static Widget outlinedPlaceForklift({Color? color, double? width, double? height}) => load('outlined-place-forklift', color, width, height);
  static Widget outlinedPlaceGps({Color? color, double? width, double? height}) => load('outlined-place-gps', color, width, height);
  static Widget outlinedPlaceLocal({Color? color, double? width, double? height}) => load('outlined-place-local', color, width, height);
  static Widget outlinedPlaceRocket({Color? color, double? width, double? height}) => load('outlined-place-rocket', color, width, height);
  static Widget outlinedPlaceRunningtruck({Color? color, double? width, double? height}) => load('outlined-place-runningtruck', color, width, height);
  static Widget outlinedPlaceTruck({Color? color, double? width, double? height}) => load('outlined-place-truck', color, width, height);
  static Widget outlinedPlaceWaze({Color? color, double? width, double? height}) => load('outlined-place-waze', color, width, height);
  static Widget outlinedProductAbandonedbag({Color? color, double? width, double? height}) => load('outlined-product-abandonedbag', color, width, height);
  static Widget outlinedProductAccessories({Color? color, double? width, double? height}) => load('outlined-product-accessories', color, width, height);
  static Widget outlinedProductBagproduct({Color? color, double? width, double? height}) => load('outlined-product-bagproduct', color, width, height);
  static Widget outlinedProductBeard({Color? color, double? width, double? height}) => load('outlined-product-beard', color, width, height);
  static Widget outlinedProductBrandsproduct({Color? color, double? width, double? height}) => load('outlined-product-brandsproduct', color, width, height);
  static Widget outlinedProductChildish({Color? color, double? width, double? height}) => load('outlined-product-childish', color, width, height);
  static Widget outlinedProductDailycare({Color? color, double? width, double? height}) => load('outlined-product-dailycare', color, width, height);
  static Widget outlinedProductEkos({Color? color, double? width, double? height}) => load('outlined-product-ekos', color, width, height);
  static Widget outlinedProductErlenmeyer({Color? color, double? width, double? height}) => load('outlined-product-erlenmeyer', color, width, height);
  static Widget outlinedProductFace({Color? color, double? width, double? height}) => load('outlined-product-face', color, width, height);
  static Widget outlinedProductHair({Color? color, double? width, double? height}) => load('outlined-product-hair', color, width, height);
  static Widget outlinedProductLashes({Color? color, double? width, double? height}) => load('outlined-product-lashes', color, width, height);
  static Widget outlinedProductLiner({Color? color, double? width, double? height}) => load('outlined-product-liner', color, width, height);
  static Widget outlinedProductLipgloss({Color? color, double? width, double? height}) => load('outlined-product-lipgloss', color, width, height);
  static Widget outlinedProductMakeup({Color? color, double? width, double? height}) => load('outlined-product-makeup', color, width, height);
  static Widget outlinedProductOutlet({Color? color, double? width, double? height}) => load('outlined-product-outlet', color, width, height);
  static Widget outlinedProductPencil({Color? color, double? width, double? height}) => load('outlined-product-pencil', color, width, height);
  static Widget outlinedProductPerfumery({Color? color, double? width, double? height}) => load('outlined-product-perfumery', color, width, height);
  static Widget outlinedProductPerfumeryfeminine({Color? color, double? width, double? height}) => load('outlined-product-perfumeryfeminine', color, width, height);
  static Widget outlinedProductPerfumerymasculine({Color? color, double? width, double? height}) => load('outlined-product-perfumerymasculine', color, width, height);
  static Widget outlinedProductPerfumerytbs({Color? color, double? width, double? height}) => load('outlined-product-perfumerytbs', color, width, height);
  static Widget outlinedProductPowder({Color? color, double? width, double? height}) => load('outlined-product-powder', color, width, height);
  static Widget outlinedProductPrimer({Color? color, double? width, double? height}) => load('outlined-product-primer', color, width, height);
  static Widget outlinedProductPromotionproduct({Color? color, double? width, double? height}) => load('outlined-product-promotionproduct', color, width, height);
  static Widget outlinedProductRelatedproducts({Color? color, double? width, double? height}) => load('outlined-product-relatedproducts', color, width, height);
  static Widget outlinedProductRepurchase({Color? color, double? width, double? height}) => load('outlined-product-repurchase', color, width, height);
  static Widget outlinedProductScent({Color? color, double? width, double? height}) => load('outlined-product-scent', color, width, height);
  static Widget outlinedProductVegan({Color? color, double? width, double? height}) => load('outlined-product-vegan', color, width, height);
  static Widget outlinedSocialAddcontact({Color? color, double? width, double? height}) => load('outlined-social-addcontact', color, width, height);
  static Widget outlinedSocialBirthday({Color? color, double? width, double? height}) => load('outlined-social-birthday', color, width, height);
  static Widget outlinedSocialCollaborate({Color? color, double? width, double? height}) => load('outlined-social-collaborate', color, width, height);
  static Widget outlinedSocialContact({Color? color, double? width, double? height}) => load('outlined-social-contact', color, width, height);
  static Widget outlinedSocialDigitalconsultant({Color? color, double? width, double? height}) => load('outlined-social-digitalconsultant', color, width, height);
  static Widget outlinedSocialGroupofpeople({Color? color, double? width, double? height}) => load('outlined-social-groupofpeople', color, width, height);
  static Widget outlinedSocialManagement({Color? color, double? width, double? height}) => load('outlined-social-management', color, width, height);
  static Widget outlinedSocialMyprofile({Color? color, double? width, double? height}) => load('outlined-social-myprofile', color, width, height);
  static Widget outlinedSocialNetwork({Color? color, double? width, double? height}) => load('outlined-social-network', color, width, height);
  static Widget outlinedSocialPerson({Color? color, double? width, double? height}) => load('outlined-social-person', color, width, height);

  static Widget aesopACustom({Color? color, double? width, double? height}) => loadLogo('aesop-a-custom', color, width, height);
  static Widget aesopAOfficialDark({Color? color, double? width, double? height}) => loadLogo('aesop-a-official-dark', color, width, height);
  static Widget aesopAOfficial({Color? color, double? width, double? height}) => loadLogo('aesop-a-official', color, width, height);
  static Widget avonACustom({Color? color, double? width, double? height}) => loadLogo('avon-a-custom', color, width, height);
  static Widget avonAOfficialDark({Color? color, double? width, double? height}) => loadLogo('avon-a-official-dark', color, width, height);
  static Widget avonAOfficial({Color? color, double? width, double? height}) => loadLogo('avon-a-official', color, width, height);
  static Widget naturaACustom({Color? color, double? width, double? height}) => loadLogo('natura-a-custom', color, width, height);
  static Widget naturaAOfficialDark({Color? color, double? width, double? height}) => loadLogo('natura-a-official-dark', color, width, height);
  static Widget naturaAOfficial({Color? color, double? width, double? height}) => loadLogo('natura-a-official', color, width, height);
  static Widget naturaBCustom({Color? color, double? width, double? height}) => loadLogo('natura-b-custom', color, width, height);
  static Widget naturaBOfficialDark({Color? color, double? width, double? height}) => loadLogo('natura-b-official-dark', color, width, height);
  static Widget naturaBOfficial({Color? color, double? width, double? height}) => loadLogo('natura-b-official', color, width, height);
  static Widget thebodyshopACustom({Color? color, double? width, double? height}) => loadLogo('thebodyshop-a-custom', color, width, height);
  static Widget thebodyshopAOfficialDark({Color? color, double? width, double? height}) => loadLogo('thebodyshop-a-official-dark', color, width, height);
  static Widget thebodyshopAOfficial({Color? color, double? width, double? height}) => loadLogo('thebodyshop-a-official', color, width, height);
  static Widget thebodyshopBCustom({Color? color, double? width, double? height}) => loadLogo('thebodyshop-b-custom', color, width, height);
  static Widget thebodyshopBOfficialDark({Color? color, double? width, double? height}) => loadLogo('thebodyshop-b-official-dark', color, width, height);
  static Widget thebodyshopBOfficial({Color? color, double? width, double? height}) => loadLogo('thebodyshop-b-official', color, width, height);
}
